<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-29T14:28:31 EET" name="Default suite" finished-at="2024-01-29T14:29:42 EET" duration-ms="70819">
    <groups>
    </groups>
    <test started-at="2024-01-29T14:28:31 EET" name="Default test" finished-at="2024-01-29T14:29:42 EET" duration-ms="70819">
      <class name="test.LoginPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:28:31 EET" name="setup" finished-at="2024-01-29T14:28:48 EET" duration-ms="16451" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testNOTSuccessfullLoginByAddingWRONGUserNameAndCorrectPassword()[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:28:48 EET" name="testNOTSuccessfullLoginByAddingWRONGUserNameAndCorrectPassword" finished-at="2024-01-29T14:28:57 EET" duration-ms="8975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNOTSuccessfullLoginByAddingWRONGUserNameAndCorrectPassword -->
        <test-method is-config="true" signature="screenshotFailure(org.testng.ITestResult)[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:28:57 EET" name="screenshotFailure" finished-at="2024-01-29T14:28:58 EET" duration-ms="1003" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testNOTSuccessfullLoginByAddingWRONGUserNameAndCorrectPassword status=SUCCESS method=LoginPageTest.testNOTSuccessfullLoginByAddingWRONGUserNameAndCorrectPassword()[pri:0, instance:test.LoginPageTest@4082ba93] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotFailure -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:28:58 EET" name="setup" finished-at="2024-01-29T14:29:10 EET" duration-ms="12183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testNOTSuccessfullLoginByAddingWRONGUserNameAndWRONGPassword()[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:29:10 EET" name="testNOTSuccessfullLoginByAddingWRONGUserNameAndWRONGPassword" finished-at="2024-01-29T14:29:19 EET" duration-ms="8850" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNOTSuccessfullLoginByAddingWRONGUserNameAndWRONGPassword -->
        <test-method is-config="true" signature="screenshotFailure(org.testng.ITestResult)[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:29:19 EET" name="screenshotFailure" finished-at="2024-01-29T14:29:20 EET" duration-ms="1055" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testNOTSuccessfullLoginByAddingWRONGUserNameAndWRONGPassword status=SUCCESS method=LoginPageTest.testNOTSuccessfullLoginByAddingWRONGUserNameAndWRONGPassword()[pri:0, instance:test.LoginPageTest@4082ba93] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotFailure -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:29:20 EET" name="setup" finished-at="2024-01-29T14:29:31 EET" duration-ms="11494" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testSuccessfullLoginByAddingCorrectUserNameAndCorrectPassword()[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:29:31 EET" name="testSuccessfullLoginByAddingCorrectUserNameAndCorrectPassword" finished-at="2024-01-29T14:29:40 EET" duration-ms="9011" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User can't login with CORRECT Data expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User can't login with CORRECT Data expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at test.LoginPageTest.testSuccessfullLoginByAddingCorrectUserNameAndCorrectPassword(LoginPageTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccessfullLoginByAddingCorrectUserNameAndCorrectPassword -->
        <test-method is-config="true" signature="screenshotFailure(org.testng.ITestResult)[pri:0, instance:test.LoginPageTest@4082ba93]" started-at="2024-01-29T14:29:40 EET" name="screenshotFailure" finished-at="2024-01-29T14:29:42 EET" duration-ms="1500" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testSuccessfullLoginByAddingCorrectUserNameAndCorrectPassword status=FAILURE method=LoginPageTest.testSuccessfullLoginByAddingCorrectUserNameAndCorrectPassword()[pri:0, instance:test.LoginPageTest@4082ba93] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotFailure -->
      </class> <!-- test.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
